FROM centos:latest

RUN dnf install -y dnf-utils git && \
    dnf config-manager --set-enabled devel --set-enabled powertools && \
    dnf builddep -y 389-ds-base && \
    dnf update -y && \
    dnf clean all

