FROM quay.io/389ds/ci-images:fedora

ENV workspace /workspace
ENV REPO https://github.com/389ds/389-ds-base

RUN dnf install -y bzip2 bind-utils coreutils-common \
cracklib-dicts hostname openssl procps-ng psmisc \
python3-pytest npm nodejs rust cargo rpm-build && \
dnf clean all

RUN mkdir -p ${workspace}/ds
WORKDIR ${workspace}}

CMD  ["/sbin/init"]
