FROM quay.io/389ds/ci-images:fedora

RUN dnf copr enable @389ds/perl-Mozilla-LDAP -y

RUN dnf install -y bzip2 bind-utils coreutils-common \
cracklib-dicts hostname openssl procps-ng psmisc \
python3-pytest npm nodejs rust cargo rpm-build \
libatomic lld libasan libubsan libdrm mesa-libgbm \
libxshmfence webkit2gtk3 passwd cockpit dbus-glib \
openldap-clients perl-Mozilla-LDAP python3-cryptography

# Temporary workaround for build issues with rust-1.71 to unblock CI
RUN dnf downgrade -y https://kojipkgs.fedoraproject.org//packages/rust/1.70.0/1.fc38/x86_64/clippy-1.70.0-1.fc38.x86_64.rpm \
https://kojipkgs.fedoraproject.org//packages/rust/1.70.0/1.fc38/x86_64/rust-1.70.0-1.fc38.x86_64.rpm \
https://kojipkgs.fedoraproject.org//packages/rust/1.70.0/1.fc38/x86_64/rust-std-static-1.70.0-1.fc38.x86_64.rpm

RUN pip3 install pytest-html pytest-custom_exit_code flaky pytest-playwright playwright python-slugify testimony
RUN playwright install

# Workaround for Firefox build that contains an older libstdc++
COPY --chmod=755 fix_pw.sh /usr/local/bin/fix_pw.sh
RUN /usr/local/bin/fix_pw.sh

# Clean up systemd services that we don't need in a container
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/*makecache.timer \
rm -f /lib/systemd/system/anaconda.target.wants/*;

ADD 99-sysctl.conf /etc/sysctl.d/99-sysctl.conf
RUN sed -i -e 's/root//g' /etc/cockpit/disallowed-users

RUN mkdir /workspace
WORKDIR /workspace

CMD  ["/sbin/init"]
