FROM quay.io/centos/centos:stream9

RUN dnf install -y dnf-utils git epel-release && \
    dnf config-manager --set-enabled crb && \
    dnf module enable -y nodejs:22 && \
    dnf builddep -y 389-ds-base && \
    dnf install -y bzip2 bind-utils coreutils-common \
    cracklib-dicts hostname openssl procps-ng psmisc \
    python3-pytest npm nodejs rust cargo rpm-build \
    libatomic lld libasan libevent-devel libtalloc-devel \
    libtevent-devel libubsan libdrm make mesa-libgbm \
    libxshmfence webkit2gtk3 passwd cockpit dbus-glib \
    openldap-clients python3-cryptography \
    net-snmp net-snmp-utils rsync && \
    dnf clean all

RUN pip3 install pytest-html pytest-custom_exit_code flaky pytest-playwright playwright python-slugify testimony
RUN playwright install
RUN cargo install cargo-license --root /usr

# Workaround for Firefox build that contains an older libstdc++
COPY --chmod=755 fix_pw.sh /usr/local/bin/fix_pw.sh
RUN /usr/local/bin/fix_pw.sh

# Clean up systemd services that we don't need in a container
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/*makecache.timer \
rm -f /lib/systemd/system/anaconda.target.wants/*;

ADD 99-sysctl.conf /etc/sysctl.d/99-sysctl.conf
ADD macros.389ds /usr/lib/rpm/macros.d/macros.389ds

RUN mkdir /workspace
WORKDIR /workspace

CMD  ["/sbin/init"]
