FROM opensuse/tumbleweed

RUN zypper mr -e repo-source && \
    zypper refresh && \
    zypper -n update && \
    zypper -n in -t pattern devel_basis && \
    zypper -n in git && \
    zypper -n si -d 389-ds
